# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file



version: 2
updates:
  # Enable version updates for npm (pour Firebase et autres dépendances npm)
  - package-ecosystem: "npm"
    directory: "/"  # Répertoire où se trouve ton package.json
    schedule:
      interval: "weekly"  # Mises à jour hebdomadaires
    commit-message:
      prefix: "chore"  # Préfixe pour les messages de commit des PRs

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
