name: CI/CD Workflows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  playwright_tests:
    name: Run Playwright Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  firebase_preview:
    name: Firebase Hosting Preview (on PR)
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    needs: playwright_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TO_SCOOBY_DO_B1B9C }}
          projectId: to-scooby-do-b1b9c
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
    defaults:
      run:
        working-directory: hosting

  firebase_deploy:
    name: Firebase Hosting Deploy (on merge to master)
    if: github.ref == 'refs/heads/master'
    needs: playwright_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TO_SCOOBY_DO_B1B9C }}
          channelId: live
          projectId: to-scooby-do-b1b9c
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
    defaults:
      run:
        working-directory: hosting
